spring:
  datasource:
    url: jdbc:mysql://rm-rj9674ua4ug74pnqt.mysql.rds.aliyuncs.com:3306/hmd?useUnicode=true&amp;characterEncoding=UTF-8
#    url: jdbc:mysql://rdsvebirzvebirzo.mysql.rds.aliyuncs.com:3306/micro-mvs
    username: hmd
    password: himedia@123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

logging:
  path: /usr/local/cloud
  level:
    root: INFO